$axure.loadCurrentPage({
  "url":"historik.html",
  "generationDate":new Date(1393428581536.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"toolbox_cont"],
  "page":{
    "packageId":"736467bf770b4756806749f4851d95b6",
    "type":"Axure:Page",
    "name":"Historik",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"366619b94c1643b187d3a4461b593c09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb3a10ef5144216b35c387aa2812929",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"1732178d14bc4f3d938eb5b0690e0912",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21817a8b89cd4f5495ab69c7d8ce3666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"b64bd581bd3447bb9957438d09bda7f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b79366c2efdd42de8ac00d5eb692a259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"eefb5f0fee1c4f3a82767b3b6fc6e3a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f98da4fdf545c180cdc3265ef686b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"67f6ef0c55a84e9999dfe488df1939c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72471b993cfc4c108640ea239dd56597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"e3d5432db1f54cc084fba73e0b32b5ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7febcec51d51409586cf685fbbeacc4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"aa0645d8117947d496d17bd362a9836b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"534ede8e882c4ce2ba20009fdfee0bd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"8c0e2d390cd2490dbd75d7b7af03921d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":140},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3584c74498ab4a9aa5ea90d3051d0fdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"713ddde28f80480eb596f7c9aa538d4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de13a536deb94977ac1f45c21969f53f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"bdd35a91b56a4355843ca2ac569ac02a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":180},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91dc7df89b374d918ade3e9a6ac9349d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"26ed428eba50441e836265f574871da5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2503d720c1e49a3a95ed6a5c27ddda7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"621c0d43980245a3ae9ee94637f53763",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":220},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"608eb87ec6094c7f89451b12ed503e87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":220},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"0ade9e65d6dc44a8907bd50f7f47a394",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":240},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f502f04880441408ea2db64accc3d9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":240},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"c3327a843561492ca7ccb0f39ea8bf9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":260},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aaaaaa100a4482cbb5fd5ff9c3e0fda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":260},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"ac079c37bdb541f4bc36531c88364b49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":280},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"995409603a3c4f89a869b6e1c1511108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":280},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"d221e5a2171a441a841bccaba6e180f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":300},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2800276f2ad442ba02fef88f1da3eca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"09751d3a4c3440ad903e61a96117897e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":320},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aecd4c6ae5b94d73a9fd6536038fb71a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":320},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}},
{
          "id":"388dcfd1d3814fedba7d3442ef6b5d21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":340},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b784a50f7ea9402e8a586f48b5fc2b2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":340},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/historik/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "366619b94c1643b187d3a4461b593c09":{
      "scriptId":"u0"},
    "cbb3a10ef5144216b35c387aa2812929":{
      "scriptId":"u1"},
    "1732178d14bc4f3d938eb5b0690e0912":{
      "scriptId":"u2"},
    "21817a8b89cd4f5495ab69c7d8ce3666":{
      "scriptId":"u3"},
    "b64bd581bd3447bb9957438d09bda7f1":{
      "scriptId":"u4"},
    "b79366c2efdd42de8ac00d5eb692a259":{
      "scriptId":"u5"},
    "eefb5f0fee1c4f3a82767b3b6fc6e3a5":{
      "scriptId":"u6"},
    "13f98da4fdf545c180cdc3265ef686b3":{
      "scriptId":"u7"},
    "67f6ef0c55a84e9999dfe488df1939c8":{
      "scriptId":"u8"},
    "72471b993cfc4c108640ea239dd56597":{
      "scriptId":"u9"},
    "e3d5432db1f54cc084fba73e0b32b5ba":{
      "scriptId":"u10"},
    "7febcec51d51409586cf685fbbeacc4c":{
      "scriptId":"u11"},
    "aa0645d8117947d496d17bd362a9836b":{
      "scriptId":"u12"},
    "534ede8e882c4ce2ba20009fdfee0bd5":{
      "scriptId":"u13"},
    "8c0e2d390cd2490dbd75d7b7af03921d":{
      "scriptId":"u14"},
    "3584c74498ab4a9aa5ea90d3051d0fdf":{
      "scriptId":"u15"},
    "713ddde28f80480eb596f7c9aa538d4e":{
      "scriptId":"u16"},
    "de13a536deb94977ac1f45c21969f53f":{
      "scriptId":"u17"},
    "bdd35a91b56a4355843ca2ac569ac02a":{
      "scriptId":"u18"},
    "91dc7df89b374d918ade3e9a6ac9349d":{
      "scriptId":"u19"},
    "26ed428eba50441e836265f574871da5":{
      "scriptId":"u20"},
    "e2503d720c1e49a3a95ed6a5c27ddda7":{
      "scriptId":"u21"},
    "621c0d43980245a3ae9ee94637f53763":{
      "scriptId":"u22"},
    "608eb87ec6094c7f89451b12ed503e87":{
      "scriptId":"u23"},
    "0ade9e65d6dc44a8907bd50f7f47a394":{
      "scriptId":"u24"},
    "8f502f04880441408ea2db64accc3d9e":{
      "scriptId":"u25"},
    "c3327a843561492ca7ccb0f39ea8bf9b":{
      "scriptId":"u26"},
    "8aaaaaa100a4482cbb5fd5ff9c3e0fda":{
      "scriptId":"u27"},
    "ac079c37bdb541f4bc36531c88364b49":{
      "scriptId":"u28"},
    "995409603a3c4f89a869b6e1c1511108":{
      "scriptId":"u29"},
    "d221e5a2171a441a841bccaba6e180f4":{
      "scriptId":"u30"},
    "f2800276f2ad442ba02fef88f1da3eca":{
      "scriptId":"u31"},
    "09751d3a4c3440ad903e61a96117897e":{
      "scriptId":"u32"},
    "aecd4c6ae5b94d73a9fd6536038fb71a":{
      "scriptId":"u33"},
    "388dcfd1d3814fedba7d3442ef6b5d21":{
      "scriptId":"u34"},
    "b784a50f7ea9402e8a586f48b5fc2b2f":{
      "scriptId":"u35"}}});