$axure.loadCurrentPage({
  "url":"dorrar.html",
  "generationDate":new Date(1393428581361.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"toolbox_cont"],
  "page":{
    "packageId":"6102fbb467654d4096a2dbc6c15e7b74",
    "type":"Axure:Page",
    "name":"Dörrar",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0c74226e388543168c2b59aa0cc42ccd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bc7484cc3ad4eb88bf0faf8c2bca420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"1c249a7abfa844a493ed2b62c90e83fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":50},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c34398606bd48d3b11627bf652ed3b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":50},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9f4280190c549a09045385e2b0b012f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":130},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vaggar/u4_line.png"}},
{
          "id":"f5683b24b5d448db8ac777ab4839d412",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8f785b072de48288e39d7d7aaf9801c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":150},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"6e8087d0bdef4b11978a873708110be5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":150},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6519ad8a96234e7f8f5919ed10117c01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":150},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"840962b90e1843c7bddd4c85c00b4443",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":230},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vaggar/u4_line.png"}},
{
          "id":"db3e5ca86bd5437091f2bfd1f58d5fd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":250},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7a01692e5bd443196f3ac4a1d47a629",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":250},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"8c4772e5a4a64a068bd5dea8095e4cbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":250},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b9369d41c2a45af87bd661d0596ec01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":250},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0f3e10435e44b8691cce27dce477177",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":330},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vaggar/u4_line.png"}},
{
          "id":"66eb1d512db842d7b90f0b9c9ef7cb57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":350},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d78e7d75f75748a695acf3121dbf172e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":350},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"aab2854ec3584862854e83a3903aacd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":350},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9670ada73cc1423988fd174205322d84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":350},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a5db47a1f8e4b70875da22a484dca9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":63.5,
              "y":12},
            "size":{
              "width":73,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07d3e664ed7640a4ae49c4832738f3d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63.5,
                  "y":12},
                "size":{
                  "width":73,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0c74226e388543168c2b59aa0cc42ccd":{
      "scriptId":"u0"},
    "5bc7484cc3ad4eb88bf0faf8c2bca420":{
      "scriptId":"u1"},
    "1c249a7abfa844a493ed2b62c90e83fc":{
      "scriptId":"u2"},
    "0c34398606bd48d3b11627bf652ed3b9":{
      "scriptId":"u3"},
    "d9f4280190c549a09045385e2b0b012f":{
      "scriptId":"u4"},
    "f5683b24b5d448db8ac777ab4839d412":{
      "scriptId":"u5"},
    "c8f785b072de48288e39d7d7aaf9801c":{
      "scriptId":"u6"},
    "6e8087d0bdef4b11978a873708110be5":{
      "scriptId":"u7"},
    "6519ad8a96234e7f8f5919ed10117c01":{
      "scriptId":"u8"},
    "840962b90e1843c7bddd4c85c00b4443":{
      "scriptId":"u9"},
    "db3e5ca86bd5437091f2bfd1f58d5fd0":{
      "scriptId":"u10"},
    "d7a01692e5bd443196f3ac4a1d47a629":{
      "scriptId":"u11"},
    "8c4772e5a4a64a068bd5dea8095e4cbf":{
      "scriptId":"u12"},
    "1b9369d41c2a45af87bd661d0596ec01":{
      "scriptId":"u13"},
    "c0f3e10435e44b8691cce27dce477177":{
      "scriptId":"u14"},
    "66eb1d512db842d7b90f0b9c9ef7cb57":{
      "scriptId":"u15"},
    "d78e7d75f75748a695acf3121dbf172e":{
      "scriptId":"u16"},
    "aab2854ec3584862854e83a3903aacd1":{
      "scriptId":"u17"},
    "9670ada73cc1423988fd174205322d84":{
      "scriptId":"u18"},
    "7a5db47a1f8e4b70875da22a484dca9e":{
      "scriptId":"u19"},
    "07d3e664ed7640a4ae49c4832738f3d6":{
      "scriptId":"u20"}}});