$axure.loadCurrentPage({
  "url":"farg.html",
  "generationDate":new Date(1393428581090.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"toolbox_cont"],
  "page":{
    "packageId":"a9a2987cba9b4f23a06ae6d31c14f8ae",
    "type":"Axure:Page",
    "name":"Färg",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0c74226e388543168c2b59aa0cc42ccd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bc7484cc3ad4eb88bf0faf8c2bca420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"1c249a7abfa844a493ed2b62c90e83fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":50},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c34398606bd48d3b11627bf652ed3b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":50},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9f4280190c549a09045385e2b0b012f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":130},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vaggar/u4_line.png"}},
{
          "id":"f5683b24b5d448db8ac777ab4839d412",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8f785b072de48288e39d7d7aaf9801c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":150},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"6e8087d0bdef4b11978a873708110be5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":150},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6519ad8a96234e7f8f5919ed10117c01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":150},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"faa44ad829ed459ca947889754d82da5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":230},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vaggar/u4_line.png"}},
{
          "id":"7e2af43912fc4a19b818e7b992e1aeb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":250},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0990cdb38850455588ceb0df76c828a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":250},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"549b2ae9395242198b0e3e6c455f3507",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":250},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77d45a0c1c4f46fba84af4e627da0774",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":250},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"947a27f1207c473595764d7d6d80ee0c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":330},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vaggar/u4_line.png"}},
{
          "id":"73a06081c18f4232bde07d87134d9763",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":350},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f18cdf9b04e4ed6bb18be68d7f8b42c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":350},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"3ec0349e52fa495284f1af12070abf3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":350},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf2c57f9bebc4972aa5bcbac6b8fad49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":350},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"debc224a1675482686e450834ab747f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":430},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vaggar/u4_line.png"}},
{
          "id":"468abacce0fa4a9a95bb13122aa78633",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":450},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c7629ea23b14c40a20a8362e4dd1358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":450},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"d38a87f7b1264ae5a0ff8c64dce9efa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":450},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6888966a9d43408bb0316894d3132757",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":450},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a74c98bf969641ef93099b018132c2f2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":530},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vaggar/u4_line.png"}},
{
          "id":"89b2f17f3e184da893c1ec68a387d2aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":550},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09d5d6b30a2c470ea39ab2d7581ee9e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":550},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"3bc27b2ee0d945aa9c886632493ea3f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":550},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"205eadbfeb944670bbf75e823b7e972d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":550},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"284f59496bec4a35accd98ad0436f177",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":630},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vaggar/u4_line.png"}},
{
          "id":"8512586431ad4807938a217afb2a34dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":650},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f0d7bf418cd4a78922c08a0a4c2c3e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":650},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"ffc93a4376dd4d3694b46652d93a2d99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":650},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ca6c89b6c9a46e19f861948aaa91df7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":650},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4eb26798b224e038214eb76a8c2f498",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":730},
            "size":{
              "width":180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/vaggar/u4_line.png"}},
{
          "id":"bb4c46a4bb0745a28ec171dd62d23db5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":750},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f028b2b35d45369f8052758a0e4d39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":750},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/vaggar/u0.png"}},
{
          "id":"9f91d7d9a9874c97beae3048ea37b9bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":750},
            "size":{
              "width":100,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52245d7a783f460a909edbd1e66491a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":750},
                "size":{
                  "width":100,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73a5f08aa5d74622877f3a122be23472",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":73.5,
              "y":12},
            "size":{
              "width":53,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a50e742cc9441f39bcb6bd5b55e8802",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73.5,
                  "y":12},
                "size":{
                  "width":53,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0c74226e388543168c2b59aa0cc42ccd":{
      "scriptId":"u0"},
    "5bc7484cc3ad4eb88bf0faf8c2bca420":{
      "scriptId":"u1"},
    "1c249a7abfa844a493ed2b62c90e83fc":{
      "scriptId":"u2"},
    "0c34398606bd48d3b11627bf652ed3b9":{
      "scriptId":"u3"},
    "d9f4280190c549a09045385e2b0b012f":{
      "scriptId":"u4"},
    "f5683b24b5d448db8ac777ab4839d412":{
      "scriptId":"u5"},
    "c8f785b072de48288e39d7d7aaf9801c":{
      "scriptId":"u6"},
    "6e8087d0bdef4b11978a873708110be5":{
      "scriptId":"u7"},
    "6519ad8a96234e7f8f5919ed10117c01":{
      "scriptId":"u8"},
    "faa44ad829ed459ca947889754d82da5":{
      "scriptId":"u9"},
    "7e2af43912fc4a19b818e7b992e1aeb0":{
      "scriptId":"u10"},
    "0990cdb38850455588ceb0df76c828a1":{
      "scriptId":"u11"},
    "549b2ae9395242198b0e3e6c455f3507":{
      "scriptId":"u12"},
    "77d45a0c1c4f46fba84af4e627da0774":{
      "scriptId":"u13"},
    "947a27f1207c473595764d7d6d80ee0c":{
      "scriptId":"u14"},
    "73a06081c18f4232bde07d87134d9763":{
      "scriptId":"u15"},
    "6f18cdf9b04e4ed6bb18be68d7f8b42c":{
      "scriptId":"u16"},
    "3ec0349e52fa495284f1af12070abf3f":{
      "scriptId":"u17"},
    "bf2c57f9bebc4972aa5bcbac6b8fad49":{
      "scriptId":"u18"},
    "debc224a1675482686e450834ab747f1":{
      "scriptId":"u19"},
    "468abacce0fa4a9a95bb13122aa78633":{
      "scriptId":"u20"},
    "3c7629ea23b14c40a20a8362e4dd1358":{
      "scriptId":"u21"},
    "d38a87f7b1264ae5a0ff8c64dce9efa8":{
      "scriptId":"u22"},
    "6888966a9d43408bb0316894d3132757":{
      "scriptId":"u23"},
    "a74c98bf969641ef93099b018132c2f2":{
      "scriptId":"u24"},
    "89b2f17f3e184da893c1ec68a387d2aa":{
      "scriptId":"u25"},
    "09d5d6b30a2c470ea39ab2d7581ee9e6":{
      "scriptId":"u26"},
    "3bc27b2ee0d945aa9c886632493ea3f9":{
      "scriptId":"u27"},
    "205eadbfeb944670bbf75e823b7e972d":{
      "scriptId":"u28"},
    "284f59496bec4a35accd98ad0436f177":{
      "scriptId":"u29"},
    "8512586431ad4807938a217afb2a34dd":{
      "scriptId":"u30"},
    "7f0d7bf418cd4a78922c08a0a4c2c3e5":{
      "scriptId":"u31"},
    "ffc93a4376dd4d3694b46652d93a2d99":{
      "scriptId":"u32"},
    "0ca6c89b6c9a46e19f861948aaa91df7":{
      "scriptId":"u33"},
    "e4eb26798b224e038214eb76a8c2f498":{
      "scriptId":"u34"},
    "bb4c46a4bb0745a28ec171dd62d23db5":{
      "scriptId":"u35"},
    "c1f028b2b35d45369f8052758a0e4d39":{
      "scriptId":"u36"},
    "9f91d7d9a9874c97beae3048ea37b9bc":{
      "scriptId":"u37"},
    "52245d7a783f460a909edbd1e66491a5":{
      "scriptId":"u38"},
    "73a5f08aa5d74622877f3a122be23472":{
      "scriptId":"u39"},
    "5a50e742cc9441f39bcb6bd5b55e8802":{
      "scriptId":"u40"}}});